### ISSUE TITLE
Occasionally tornado likes to spit stack traces to the cell

### ISSUE THREAD

**Issue by ericdill** [coiled/coiled-issues#22]
![image](https://user-images.githubusercontent.com/6223243/86636615-824e5400-bfa2-11ea-8918-c7db5d483e21.png)

Seemingly unrelated to the cluster creation, tornado spit out a bunch of stack traces:
```
Creating cluster. This takes about a minute

tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <zmq.eventloop.ioloop.ZMQIOLoop object at 0x7f312d1bd2e0>>, <Task finished name='Task-23' coro=<CoiledCluster._close() done, defined at /home/ericdill/dev/coiled/cloud/python-api/coiled/cluster.py:109> exception=AttributeError("'CoiledCluster' object has no attribute 'scheduler_comm'")>)
Traceback (most recent call last):
  File "/home/ericdill/miniconda/envs/coiled/lib/python3.8/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/ericdill/miniconda/envs/coiled/lib/python3.8/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/ericdill/dev/coiled/cloud/python-api/coiled/cluster.py", line 113, in _close
    await super()._close()
  File "/home/ericdill/miniconda/envs/coiled/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 83, in _close
    if self.scheduler_comm:
AttributeError: 'CoiledCluster' object has no attribute 'scheduler_comm'
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <zmq.eventloop.ioloop.ZMQIOLoop object at 0x7f312d1bd2e0>>, <Task finished name='Task-22' coro=<CoiledCluster._close() done, defined at /home/ericdill/dev/coiled/cloud/python-api/coiled/cluster.py:109> exception=AttributeError("'CoiledCluster' object has no attribute 'scheduler_comm'")>)
Traceback (most recent call last):
  File "/home/ericdill/miniconda/envs/coiled/lib/python3.8/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/ericdill/miniconda/envs/coiled/lib/python3.8/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/ericdill/dev/coiled/cloud/python-api/coiled/cluster.py", line 113, in _close
    await super()._close()
  File "/home/ericdill/miniconda/envs/coiled/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 83, in _close
    if self.scheduler_comm:
AttributeError: 'CoiledCluster' object has no attribute 'scheduler_comm'
```

**Comment by ericdill** [comment]
git sha for checkout: `7da8a3b`

**Comment by mrocklin** [comment]
Fixed by https://github.com/dask/distributed/pull/3945

**Comment by jrbourbeau** [comment]
Closing as https://github.com/dask/distributed/pull/3945 has been merged and released. Thanks for reporting @ericdill!
