### ISSUE TITLE
coiled module does not work with python 3.6.9 (default ubuntu 18.04 version)

### ISSUE THREAD

**Issue by sheer-coiled** [coiled/coiled-issues#35]
A plain ubuntu 18.04 install with the default python3 env does not work with coiled.  This is easy to reproduce using docker by opening an interactive container:

```
docker run -it --rm ubuntu:18.04 bash
```
Then run in the container:
```
apt-get update
apt-get upgrade
apt-get install python3-pip python3-dev
pip3 install coiled
# python3 complains if locale is not set to utf-8
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
```
Finally try coiled login:
```
root@37842c14a534:/# coiled login
Traceback (most recent call last):
  File "/usr/local/bin/coiled", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/coiled/cli/login.py", line 14, in login
    asyncio.run(handle_credentials(server, save=True))
AttributeError: module 'asyncio' has no attribute 'run'
```
Repeating the above steps but replacing 18.04 with 20.04 works and does not generate any error.

The python version in 18.04 is 3.6.9 while for 20.04 its 3.8.*.

**Comment by necaris** [comment]
@sheer-coiled this should be closed by https://github.com/coiled/cloud/pull/616 -- we were using a few 3.7+ features, but didn't need to. @jrbourbeau have we released since this was merged?

**Comment by jrbourbeau** [comment]
> @jrbourbeau have we released since this was merged?

We have not. I'll ping this issue after we release next

**Comment by jrbourbeau** [comment]
Closing as `coiled==0.0.18` added back support for Python 3.6. Thanks for reporting @sheer-coiled!
