### ISSUE TITLE
Authentication credentials were not provided

### ISSUE THREAD

**Issue by jose-moralez** [coiled/coiled-issues#38]
Hi. I had gone through the login process before, but now when I try to create a software environment I get: `Exception: {'detail': 'Authentication credentials were not provided.'}`. So I tried `coiled login` from the CLI, entered my token and got the same exception. Here's the full traceback:

```
Please login to https://dev.coiledhq.com/profile to get your token
Token: 
Traceback (most recent call last):
  File "/home/jose_morales/miniconda3/envs/minif/bin/coiled", line 10, in <module>
    sys.exit(cli())
  File "/home/jose_morales/miniconda3/envs/minif/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jose_morales/miniconda3/envs/minif/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jose_morales/miniconda3/envs/minif/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jose_morales/miniconda3/envs/minif/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jose_morales/miniconda3/envs/minif/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jose_morales/miniconda3/envs/minif/lib/python3.7/site-packages/coiled/cli/login.py", line 15, in login
    asyncio.run(handle_credentials(server, save=True))
  File "/home/jose_morales/miniconda3/envs/minif/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/jose_morales/miniconda3/envs/minif/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/jose_morales/miniconda3/envs/minif/lib/python3.7/site-packages/coiled/utils.py", line 106, in handle_credentials
    raise Exception(data)
Exception: {'detail': 'Authentication credentials were not provided.'}
```

Am I doing something wrong? I get this error even if I submit some gibberish as the token.

**Comment by mrocklin** [comment]
Hi @jose-moralez !

I apologize for the error.  We've been moving quickly recently.  

I recommend upgrading Coiled, removing your config file, and logging in again

```
rm ~/.config/dask/coiled.yaml
pip install coiled --upgrade
coiled login
```

**Comment by jose-moralez** [comment]
I did try looking for a file like this but was looking for `~/.config/coiled`. Thank you, Matt!

**Comment by mrocklin** [comment]
It's a good guess!  We're just lazy right now and still leveraging the Dask
config system :)
