### ISSUE TITLE
Traceback on coiled.Cluster

### ISSUE THREAD

**Issue by TomAugspurger** [coiled/coiled-issues#40]
cc @necaris 

<details>

```
In [2]: import coiled
   ...: cluster = coiled.Cluster(n_workers=10)
   ...:
   ...: from dask.distributed import Client
   ...: client = Client(cluster)
   ...: print("Dashboard:", client.dashboard_link)
   ...:
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-2-4af276e703de> in <module>
      1 import coiled
----> 2 cluster = coiled.Cluster(n_workers=10)
      3
      4 from dask.distributed import Client
      5 client = Client(cluster)

~/miniconda3/envs/coiled-coiled-default/lib/python3.8/site-packages/coiled/cluster.py in __init__(self, n_workers, configuration, name, asynchronous, cloud, account, shutdown_on_close)
     67
     68         if not self.asynchronous:
---> 69             self.sync(self._start)
     70
     71     @property

~/miniconda3/envs/coiled-coiled-default/lib/python3.8/site-packages/distributed/deploy/cluster.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    168             return future
    169         else:
--> 170             return sync(self.loop, func, *args, **kwargs)
    171
    172     async def _get_logs(self, scheduler=True, workers=True):

~/miniconda3/envs/coiled-coiled-default/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    337     if error[0]:
    338         typ, exc, tb = error[0]
--> 339         raise exc.with_traceback(tb)
    340     else:
    341         return result[0]

~/miniconda3/envs/coiled-coiled-default/lib/python3.8/site-packages/distributed/utils.py in f()
    321             if callback_timeout is not None:
    322                 future = asyncio.wait_for(future, callback_timeout)
--> 323             result[0] = yield future
    324         except Exception as exc:
    325             error[0] = sys.exc_info()

~/miniconda3/envs/coiled-coiled-default/lib/python3.8/site-packages/tornado/gen.py in run(self)
    733
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/miniconda3/envs/coiled-coiled-default/lib/python3.8/site-packages/coiled/cluster.py in _start(self)
    113
    114         if self._start_n_workers:
--> 115             await self._scale(self._start_n_workers)
    116
    117         self.security, info = await self.cloud.security(name=self.name, account=self.account)  # type: ignore

~/miniconda3/envs/coiled-coiled-default/lib/python3.8/site-packages/coiled/cluster.py in _scale(self, n)
    157
    158     async def _scale(self, n: int) -> None:
--> 159         await self.cloud.scale(account=self.account, name=self.name, n=n)  # type: ignore
    160
    161     def scale(self, n: int) -> None:

~/miniconda3/envs/coiled-coiled-default/lib/python3.8/site-packages/coiled/core.py in _scale(self, name, n, account)
    391         if response.status >= 400:
    392             text = await response.text()
--> 393             raise Exception(text)
    394
    395     def scale(self, name: str, n: int, account: str = None) -> None:

Exception: IndexError at /api/v1/tomaugspurger/clusters/TomAugspurger-1af2e944-8/scale/
list index out of range

Request Method: PATCH
Request URL: https://beta.coiledhq.com/api/v1/tomaugspurger/clusters/TomAugspurger-1af2e944-8/scale/
Django Version: 3.0.9
Python Executable: /opt/conda/bin/python
Python Version: 3.8.2
Python Path: ['.', '/opt/conda/bin', '/opt/conda/lib/python38.zip', '/opt/conda/lib/python3.8', '/opt/conda/lib/python3.8/lib-dynload', '/opt/conda/lib/python3.8/site-packages']
Server time: Mon, 10 Aug 2020 18:53:13 +0000
Installed Applications:
['whitenoise.runserver_nostatic',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.sessions',
 'django.contrib.staticfiles',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.github',
 'invitations',
 'channels',
 'corsheaders',
 'dj_rest_auth',
 'rest_framework',
 'rest_framework.authtoken',
 'api.apps.ApiConfig',
 'cloud.apps.CloudConfig',
 'users.apps.UsersConfig',
 'ddtrace.contrib.django']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django_structlog.middlewares.RequestMiddleware']


Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/conda/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/conda/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/ddtrace/contrib/django/patch.py", line 80, in wrapper
    return func(mod, pin, wrapped, instance, args, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/ddtrace/contrib/django/patch.py", line 252, in wrapped
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/ddtrace/contrib/django/patch.py", line 80, in wrapper
    return func(mod, pin, wrapped, instance, args, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/ddtrace/contrib/django/patch.py", line 252, in wrapped
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/ddtrace/contrib/django/patch.py", line 80, in wrapper
    return func(mod, pin, wrapped, instance, args, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/ddtrace/contrib/django/patch.py", line 252, in wrapped
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/opt/conda/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/conda/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/opt/conda/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/ddtrace/contrib/django/patch.py", line 80, in wrapper
    return func(mod, pin, wrapped, instance, args, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/ddtrace/contrib/django/patch.py", line 252, in wrapped
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/rest_framework/generics.py", line 229, in patch
    return self.partial_update(request, *args, **kwargs)
  File "./cloud/views/clusters.py", line 81, in update
    CloudConfig.backend.scale(
  File "./backends/core.py", line 149, in scale
    return self.sync(  # type: ignore
  File "./backends/core.py", line 72, in sync
    return sync(self.io_loop, func, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/opt/conda/lib/python3.8/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "./backends/ecs.py", line 591, in _scale
    scheduler_address = await self._network_addresses(scheduler["taskArns"][-1])

Exception Type: IndexError at /api/v1/tomaugspurger/clusters/TomAugspurger-1af2e944-8/scale/
Exception Value: list index out of range
Request information:
USER: TomAugspurger

GET: No GET data

POST:
worker_count_requested = '10'

FILES: No FILES data

COOKIES: No cookie data

META:
CONTENT_LENGTH = '25'
CONTENT_TYPE = 'application/x-www-form-urlencoded'
HTTP_ACCEPT = '*/*'
HTTP_ACCEPT_ENCODING = 'gzip, deflate'
HTTP_AUTHORIZATION = 'Token 9be034b5abf53e1fa6454544f368217110c657c9'
HTTP_CLIENT_VERSION = '0.0.18'
HTTP_HOST = 'beta.coiledhq.com'
HTTP_USER_AGENT = 'Python/3.8 aiohttp/3.6.2'
HTTP_X_AMZN_TRACE_ID = 'Root=1-5f319799-e0859505427f5980c75ec87f'
HTTP_X_FORWARDED_FOR = '173.17.254.127'
HTTP_X_FORWARDED_PORT = '443'
HTTP_X_FORWARDED_PROTO = 'https'
PATH_INFO = '/api/v1/tomaugspurger/clusters/TomAugspurger-1af2e944-8/scale/'
QUERY_STRING = ''
REMOTE_ADDR = '10.1.13.132'
REMOTE_HOST = '10.1.13.132'
REMOTE_PORT = 38564
REQUEST_METHOD = 'PATCH'
SCRIPT_NAME = ''
SERVER_NAME = '10.1.2.196'
SERVER_PORT = '8000'
wsgi.multiprocess = True
wsgi.multithread = True

Settings:
Using settings module cloud.settings.dev
ABSOLUTE_URL_OVERRIDES = {}
ACCOUNT_ADAPTER = 'invitations.models.InvitationsAdapter'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_SUBJECT_PREFIX = ''
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = True
ADMINS = []
ALLAUTH_EMAIL_SUBJECT_PREFIX = ''
ALLOWED_HOSTS = ['beta.coiledhq.com', '*', '*']
APPEND_SLASH = True
ASGI_APPLICATION = 'cloud.routing.application'
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend', 'allauth.account.auth_backends.AuthenticationBackend']
AUTH_PASSWORD_VALIDATORS = '********************'
AUTH_USER_MODEL = 'users.User'
AWS_COMMON_TAGS = {}
AWS_DEFAULT_REGION = 'us-east-2'
AWS_RESOURCE_PREFIX = ''
AWS_ROLE_POLICIES_FOR_CLUSTERS = ['arn:aws:iam::769926636128:policy/dev-cluster-role-s3-read-policy']
AWS_SES_REGION = 'us-east-1'
BASE_DIR = PosixPath('/usr/src/app')
CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_KEY_PREFIX = '********************'
CACHE_MIDDLEWARE_SECONDS = 600
CHANNEL_LAYERS = {'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'}}
CLUSTER_BACKEND = 'backends.ecs.ClusterManager'
COILED_MIN_CLIENT_VERSION = '0.0.16'
COILED_PERIODIC_CALLBACKS = [{'callable': 'cloud.callbacks.SyncBackendStatus', 'interval': 3000.0}, {'callable': 'cloud.callbacks.CleanUpImages', 'interval': 7200000}, {'callable': 'cloud.callbacks.Heartbeat', 'interval': 200}]
CORS_ORIGIN_ALLOW_ALL = True
CSRF_COOKIE_AGE = 31449600
CSRF_COOKIE_DOMAIN = None
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_PATH = '/'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS = []
CSRF_USE_SESSIONS = False
CUSTOM_BUILD_CONTEXT_BUCKET = 'coiled-build-artifacts'
CUSTOM_BUILD_CONTEXT_BUCKET_READ_POLICY = 'arn:aws:iam::769926636128:policy/dev-build-artifact-read'
CUSTOM_BUILD_EXECUTION_ROLE = 'coiled-image-builder'
CUSTOM_BUILD_SUBNETS = ['subnet-0512d5d3e407dd76a']
CUSTOM_BUILD_TASK_DEFINITION_NAME = 'dev-builder'
DATABASES = {'default': {'ENGINE': 'django.db.backends.postgresql_psycopg2', 'HOST': 'dev.cluster-cevfi4mgsznb.us-east-2.rds.amazonaws.com', 'PORT': 5432, 'NAME': 'coiled_cloud', 'USER': 'cloud', 'PASSWORD': '********************', 'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True, 'CONN_MAX_AGE': 0, 'OPTIONS': {}, 'TIME_ZONE': None, 'TEST': {'CHARSET': None, 'COLLATION': None, 'NAME': None, 'MIRROR': None}}}
DATABASE_ROUTERS = []
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000
DATETIME_FORMAT = 'N j, Y, P'
DATETIME_INPUT_FORMATS = ['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M', '%Y-%m-%d', '%m/%d/%Y %H:%M:%S', '%m/%d/%Y %H:%M:%S.%f', '%m/%d/%Y %H:%M', '%m/%d/%Y', '%m/%d/%y %H:%M:%S', '%m/%d/%y %H:%M:%S.%f', '%m/%d/%y %H:%M', '%m/%d/%y']
DATE_FORMAT = 'N j, Y'
DATE_INPUT_FORMATS = ['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', '%b %d %Y', '%b %d, %Y', '%d %b %Y', '%d %b, %Y', '%B %d %Y', '%B %d, %Y', '%d %B %Y', '%d %B, %Y']
DD_API_KEY = '********************'
DD_ENABLED = True
DEBUG = True
DEBUG_PROPAGATE_EXCEPTIONS = False
DECIMAL_SEPARATOR = '.'
DEFAULT_ACCESS_LIMIT = 100
DEFAULT_ACCOUNT_ACCESS_LIMIT = 100
DEFAULT_CHARSET = 'utf-8'
DEFAULT_EXCEPTION_REPORTER_FILTER = 'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
DEFAULT_FROM_EMAIL = 'Coiled Team <info@coiledhq.com>'
DEFAULT_INDEX_TABLESPACE = ''
DEFAULT_SOFTWARE_BASE_IMAGE = 'continuumio/miniconda3:4.8.2'
DEFAULT_TABLESPACE = ''
DEFAULT_VPC = 'vpc-04a97378d31f30f1c'
DISALLOWED_USER_AGENTS = []
ECS_CLUSTER_NAME = 'dev'
ECS_EXECUTION_ROLE_NAME = 'dev-ecs-task-execution-role'
EMAIL_BACKEND = 'django_amazon_ses.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_HOST_PASSWORD = '********************'
EMAIL_HOST_USER = ''
EMAIL_PORT = 25
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = '********************'
EMAIL_SUBJECT_PREFIX = '[Django] '
EMAIL_TIMEOUT = None
EMAIL_USE_LOCALTIME = False
EMAIL_USE_SSL = False
EMAIL_USE_TLS = False
ENV_NAME = 'dev'
FE_BASE_DIR = PosixPath('/usr/src/app/frontend')
FILE_CHARSET = 'utf-8'
FILE_UPLOAD_DIRECTORY_PERMISSIONS = None
FILE_UPLOAD_HANDLERS = ['django.core.files.uploadhandler.MemoryFileUploadHandler', 'django.core.files.uploadhandler.TemporaryFileUploadHandler']
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440
FILE_UPLOAD_PERMISSIONS = 420
FILE_UPLOAD_TEMP_DIR = None
FIRST_DAY_OF_WEEK = 0
FIXTURE_DIRS = []
FORCE_SCRIPT_NAME = None
FORMAT_MODULE_PATH = None
FORM_RENDERER = 'django.forms.renderers.DjangoTemplates'
IGNORABLE_404_URLS = []
INSTALLED_APPS = ['whitenoise.runserver_nostatic', 'django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.messages', 'django.contrib.sites', 'django.contrib.sessions', 'django.contrib.staticfiles', 'allauth', 'allauth.account', 'allauth.socialaccount', 'allauth.socialaccount.providers.github', 'invitations', 'channels', 'corsheaders', 'dj_rest_auth', 'rest_framework', 'rest_framework.authtoken', 'api.apps.ApiConfig', 'cloud.apps.CloudConfig', 'users.apps.UsersConfig', 'ddtrace.contrib.django']
INTERNAL_IPS = ['127.0.0.1']
INVITATIONS_ACCEPT_INVITE_AFTER_SIGNUP = True
INVITATIONS_CONFIRM_INVITE_ON_GET = True
INVITATIONS_EMAIL_SUBJECT_PREFIX = ''
INVITATIONS_GONE_ON_ACCEPT_ERROR = False
INVITATIONS_INVITATION_EXPIRY = 7
INVITATIONS_LOGIN_REDIRECT = '/login'
INVITATIONS_SIGNUP_REDIRECT = '/login'
LANGUAGES = [('af', 'Afrikaans'), ('ar', 'Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')]
LANGUAGES_BIDI = ['he', 'ar', 'fa', 'ur']
LANGUAGE_CODE = 'en-us'
LANGUAGE_COOKIE_AGE = None
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_HTTPONLY = False
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_PATH = '/'
LANGUAGE_COOKIE_SAMESITE = None
LANGUAGE_COOKIE_SECURE = False
LOCALE_PATHS = []
LOGGING = {'version': 1, 'disable_existing_loggers': True, 'formatters': {'json': {'()': <class 'structlog.stdlib.ProcessorFormatter'>, 'processor': <structlog.processors.JSONRenderer object at 0x7f2959fb6280>, 'foreign_pre_chain': [<structlog.processors.TimeStamper object at 0x7f2959fb5940>, <function add_logger_name at 0x7f295a02a9d0>, <function add_log_level at 0x7f295a02a8b0>, <structlog.processors.StackInfoRenderer object at 0x7f295a071a60>, <function format_exc_info at 0x7f295a01f0d0>, <structlog.processors.UnicodeDecoder object at 0x7f2959fb6130>, <structlog.processors.ExceptionPrettyPrinter object at 0x7f2959fb6100>]}, 'console': {'()': <class 'structlog.stdlib.ProcessorFormatter'>, 'processor': <structlog.dev.ConsoleRenderer object at 0x7f2959fb6250>, 'foreign_pre_chain': [<structlog.processors.TimeStamper object at 0x7f2959fb5940>, <function add_logger_name at 0x7f295a02a9d0>, <function add_log_level at 0x7f295a02a8b0>, <structlog.processors.StackInfoRenderer object at 0x7f295a071a60>, <function format_exc_info at 0x7f295a01f0d0>, <structlog.processors.UnicodeDecoder object at 0x7f2959fb6130>, <structlog.processors.ExceptionPrettyPrinter object at 0x7f2959fb6100>]}}, 'handlers': {'console': {'class': 'logging.StreamHandler', 'formatter': 'json', 'stream': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>}, 'plain': {'class': 'logging.StreamHandler'}}, 'root': {'handlers': ['console'], 'level': 'INFO', 'propagate': False}, 'loggers': {'django': {'handlers': ['console'], 'level': 'INFO', 'propagate': False}, 'dask': {'handlers': ['console'], 'level': 'INFO', 'propagate': False}, 'distributed': {'handlers': ['console'], 'level': 'INFO', 'propagate': False}, 'django.channels.server': {'handlers': ['plain'], 'level': 'WARNING', 'propagate': False}, 'ddtrace.internal': {'handlers': ['console'], 'level': 'CRITICAL', 'propagate': False}, 'cloud': {'handlers': ['console'], 'level': 'DEBUG', 'propagate': False}, 'backends': {'handlers': ['console'], 'level': 'DEBUG', 'propagate': False}, 'users': {'handlers': ['console'], 'level': 'DEBUG', 'propagate': False}, 'api': '********************', 'clusters': {'handlers': ['console'], 'level': 'DEBUG', 'propagate': False}}}
LOGGING_CONFIG = 'logging.config.dictConfig'
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login'
LOGOUT_REDIRECT_URL = '/'
MAGIC_VERSION_SENT_BY_FRONTEND = 'coiled-frontend-js'
MANAGERS = []
MEDIA_ROOT = ''
MEDIA_URL = ''
MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'
MIDDLEWARE = ['corsheaders.middleware.CorsMiddleware', 'django.middleware.security.SecurityMiddleware', 'whitenoise.middleware.WhiteNoiseMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware', 'django_structlog.middlewares.RequestMiddleware']
MIGRATION_MODULES = {}
MONTH_DAY_FORMAT = 'F j'
NUMBER_GROUPING = 0
PASSWORD_HASHERS = '********************'
PASSWORD_RESET_TIMEOUT_DAYS = '********************'
PREPEND_WWW = False
PRETTY_LOGGING = False
REST_FRAMEWORK = {'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination', 'PAGE_SIZE': 25, 'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'], 'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.TokenAuthentication', 'rest_framework.authentication.SessionAuthentication']}
ROOT_URLCONF = 'cloud.urls'
SECRET_KEY = '********************'
SECURE_BROWSER_XSS_FILTER = False
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_HSTS_SECONDS = 0
SECURE_PROXY_SSL_HEADER = "('HTTP_X_FORWARDED_PROTO', 'https')"
SECURE_REDIRECT_EXEMPT = []
SECURE_REFERRER_POLICY = None
SECURE_SSL_HOST = None
SECURE_SSL_REDIRECT = False
SERVER_EMAIL = 'Coiled Team <info@coiledhq.com>'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 1209600
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_FILE_PATH = None
SESSION_SAVE_EVERY_REQUEST = False
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_MODULE = 'cloud.settings.dev'
SHARED_TOKENS = '********************'
SHORT_DATETIME_FORMAT = 'm/d/Y P'
SHORT_DATE_FORMAT = 'm/d/Y'
SHOW_STOPPED_CLUSTERS_AGE = 24
SIGNING_BACKEND = 'django.core.signing.TimestampSigner'
SILENCED_SYSTEM_CHECKS = []
SITE_ID = 1
SOCIALACCOUNT_AUTO_SIGNUP = False
STARTUP_GRACE_PERIOD_SECONDS = 30
STATICFILES_DIRS = [PosixPath('/usr/src/app/frontend/dist'), PosixPath('/usr/src/app/static')]
STATICFILES_FINDERS = ['django.contrib.staticfiles.finders.FileSystemFinder', 'django.contrib.staticfiles.finders.AppDirectoriesFinder']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_DIR = PosixPath('/usr/src/app/static')
STATIC_ROOT = PosixPath('/usr/src/app/collected_static')
STATIC_URL = '/static/'
SYNC_BACKEND_STATUS_FREQUENCY_MS = 3000.0
TEMPLATES = [{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': [PosixPath('/usr/src/app/frontend/dist'), PosixPath('/usr/src/app/cloud/templates')], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages']}}]
TESTING = False
TEST_AGAINST_AWS = False
TEST_NON_SERIALIZED_APPS = []
TEST_RUNNER = 'django.test.runner.DiscoverRunner'
THOUSAND_SEPARATOR = ','
TIME_FORMAT = 'P'
TIME_INPUT_FORMATS = ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_THOUSAND_SEPARATOR = False
USE_TZ = True
USE_X_FORWARDED_HOST = False
USE_X_FORWARDED_PORT = False
WHITENOISE_KEEP_ONLY_HASHED_FILES = True
WSGI_APPLICATION = 'cloud.wsgi.application'
X_FRAME_OPTIONS = 'DENY'
YEAR_MONTH_FORMAT = 'F Y'


You're seeing this error because you have DEBUG = True in your
Django settings file. Change that to False, and Django will
display a standard page generated by the handler for this status code.
```

</details>

**Comment by necaris** [comment]
@TomAugspurger :crossed_fingers: believe this is fixed now, and the fix has been deployed. Would love it if you could try again.

**Comment by TomAugspurger** [comment]
Thanks Rami. Confirmed that it's working well for me.
