### ISSUE TITLE
CLI Login Faliure

### ISSUE THREAD

**Issue by quasiben** [coiled/coiled-issues#60]
Using coiled 0.0.22 I can't seem to login:

_note: I am provide a valid token supplied from `/profile`

```
❯ coiled login
Please login to https://beta.coiledhq.com/profile to get your token
Token:

Traceback (most recent call last):
  File "/Users/bzaitlen/miniconda3/envs/coiled/bin/coiled", line 8, in <module>
    sys.exit(cli())
  File "/Users/bzaitlen/miniconda3/envs/coiled/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/bzaitlen/miniconda3/envs/coiled/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/bzaitlen/miniconda3/envs/coiled/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/bzaitlen/miniconda3/envs/coiled/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/bzaitlen/miniconda3/envs/coiled/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/bzaitlen/miniconda3/envs/coiled/lib/python3.7/site-packages/coiled/cli/login.py", line 17, in login
    handle_credentials(server=server, token=token, save=True)
  File "/Users/bzaitlen/miniconda3/envs/coiled/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/bzaitlen/miniconda3/envs/coiled/lib/python3.7/site-packages/coiled/utils.py", line 113, in handle_credentials
    raise Exception(data)
Exception: {'detail': 'Authentication credentials were not provided.'}
 ❲c❳ coiled  ~ 
```

**Comment by quasiben** [comment]
Worked.  Thanks @mrocklin
